import '../globals.css'

export const metadata = {
  title: 'Society Managment System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return <section>{children}</section>
}
