import Navbar from '../components/Navbar'
import '../globals.css'

export const metadata = {
  title: 'Society Managment System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link href='https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;600;700&display=swap' rel='stylesheet' />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
